---
development:
  cloud_name: dwsqw6mhk
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET_KEY"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dwsqw6mhk
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET_KEY"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dwsqw6mhk
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET_KEY"] %>
  enhance_image_tag: true
  static_image_support: false
